spring:
  data:
    mongodb:
      host: localhost
      port: 27019
#      database: demoDB
#      username: usr
#      password: pwd
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none